const FORM_VALIDATION_RULES = 
{
    "email":
    {
        "min_length":3,
        "max_length":40,
        "match":/([-\.a-z0-9])*?@([a-z])+?([-\.a-z0-9])*?\.??([-\.a-z0-9])*/ig,
    },
    "name":
    {
        "min_length":3,
        "max_length":40,
    },
    "forename":
    {
        "min_length":3,
        "max_length":40,
    },
    "feedback":
    {
        
    },
    "password":
    {
        "min_length":6,
        "max_length":40,
        "match":/^([a-z0-9]){6,}$/ig,
    },
};