<?
define("DB_URL","localhost");
define("DB_NAME","bwt_test");
define("DB_LOGIN","mysql");
define("DB_PASSWORD","mysql");
define("WEATHER_URL","weather");
define("FEEDBACK_URL","feedback");
define("HOME_URL","/");
define("AUTHORIZATION_URL","authorization");
define("REGISTRATION_URL","registration");